name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: run init script
      env: 
        mongo_db_URI: ${{ secrets.mongo_db_URI }}
      run: |
        sh init.sh
    - name: npm install, build, and lint
      run: |
        ./init.sh
        npm ci
        npm run build --if-present
        npm run lint
      env:
        CI: true
